### ISSUE TITLE
Request for extra rangeSet

### ISSUE THREAD

**Issue by mrPassion78** [Mogli12/VehicleControlAddon#422]
I recently switched from RMT to VCA gears, sins RMT and VCA along with REA doesn't go to well for me, it causes vehicles to fly off and the tank is empty instant.
So there for i was wondering if it would be possible to add in a second RangSet , so that the configs can be easier to setup and shift through .

And would it be possible to get a " LH " in the 4G section of shifter settings 

keep up the good work, this mod has already become awesome 🥇

**Comment by Fracking** [comment]
Hey mrPassion78,
my post is not really on topic. You mentioned the "vehicles fly off and instantly empty the fueltank" behavior. I had the same issue, but I don't have RMT installed (just VCA and REA). I can't reproduce it, but it did happen a couple of times. Since nobody mentioned it in a bugreport, I thought it might be some mod conflict. I didn't bother trying to find the issue. Nice to know I'm not the only one with that issue.
