### ISSUE TITLE
Can we all speak in one language?

### ISSUE THREAD

**Issue by KCHARRO** [Mogli12/VehicleControlAddon#461]
Hello guys....

If it's not a bother for everyone, could we write all the issues in English?

I do not see bad that everyone speaks in their native language, but if we do it here, it looks a lot of mess, my language is Spanish, however I publish in English, the majority of users from all countries know some English.

It is not a complaint, just a suggestion to make this look more organized, and easier for everyone to understand ...

Greetings to all

**Comment by Mogli12** [comment]
HI @KCHARRO ,

I think you are right. I would like to encourage everyone to write issues in English because most people can understand it better.

Nevertheless, I know that there are people that are not so comfortable writing issues in English. I am a native German speaker. I will try to add an English summary to important or interesting issues.

Best regards,
Stefan

**Comment by KCHARRO** [comment]
@Mogli12 

Thank you for your attention, many of us would appreciate it very much...
